<a href="https://colab.research.google.com/github/Diego-rp/Google-Colab/blob/master/05%20-%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Lambda School Data Science - Intro to Python  
---
# 05 - Numpy
---



##STOP! BEFORE GOING ANY FURTHER...  


1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to "FIRSTNAME_LASTNAME_1_2"  

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and submit. Be sure to do this for ***every*** assignment!



### Import Numpy as Np

In [0]:
import numpy as np

### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [6]:
arr = np.random.randint(100, size=(5,3))
print(arr)


[[47 79 38]
 [50 88 32]
 [94 41 83]
 [76 50 70]
 [ 9 89 54]]


### Array practice
Run each of these in their own code cell and comment it accordingly:

*  Return the first row
*  Return the last column
*  Return the third column values from the 4th and 5th rows
*  Multiply every value in the array by 2
*  Divide every value by 3
*  Increase the values in the first row by 12
* Calculate the mean of the first column
* Calculate the median of the array _after_ removing the 2 smallest values in the array
* Calculate the standard deviation of the first 3 rows
* Return values in the second column greater than 25
* Return values in the array under 40

In [0]:
# Return the first row:

In [7]:
arr[0]

array([47, 79, 38])

In [0]:
# Return the last column:

In [9]:
arr[:,-1]

array([38, 32, 83, 70, 54])

In [10]:
# Return the third column values from the 4th and 5th rows:
arr[3:5,2]

array([70, 54])

In [0]:
# Multiply every value in the array by 2:

In [11]:
arr *2 

array([[ 94, 158,  76],
       [100, 176,  64],
       [188,  82, 166],
       [152, 100, 140],
       [ 18, 178, 108]])

In [12]:
# Divide every value by 3
arr/3

array([[15.66666667, 26.33333333, 12.66666667],
       [16.66666667, 29.33333333, 10.66666667],
       [31.33333333, 13.66666667, 27.66666667],
       [25.33333333, 16.66666667, 23.33333333],
       [ 3.        , 29.66666667, 18.        ]])

In [0]:
# Increase the values in the first row by 12:

In [13]:
arr[0]+12

array([59, 91, 50])

In [0]:
# Calculate the mean of the first column:

In [14]:
np.mean(arr[:,0])

55.2

In [0]:
# Calculate the median of the array after removing the 2 smallest values in the array:

In [29]:
np.median(sorted(arr.flatten())[2:])


70.0

In [0]:
# Calculate the standard deviation of the first 3 rows:

In [33]:
np.std(arr[:3])

22.88133640230735

In [0]:
# Return values in the second column greater than 25:

In [44]:
x=arr[:,1]
x[x>25]

array([79, 88, 41, 50, 89])

In [0]:
# Return values in the array under 40:

In [46]:
arr[arr<40]

array([38, 32,  9])